Month 7/step 2
EukleidesRUS/react-burger pull request #1
Opened 2022-07-07 00:21 UTC by EukleidesRUS

1st review

2022-07-07 06:14 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.

Вынужден отклонить работу без потери итерации, так как проект запускается с ошибкой. Исправьте это и ваша работа будет приянта.

<img width="1437" alt="Снимок экрана 2022-07-07 в 08 55 06" src="https://user-images.githubusercontent.com/60173362/177702130-5b103eb2-49d6-4dbb-bfe3-7025e6b10436.png">

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2022-07-07 06:14 UTC, andryxxa93 commented on src/utils/api/api.jsx
> +      console.log(err);
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией. А ошибку лучше записывать в state и показывать пользователю, чтобы он понимал, что происходит.

2022-07-07 06:14 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +const BurgerConstructor = (props) => {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2022-07-07 06:14 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        <IngredientsCategory data={props.data} type="bun" tabRef={bunRef} name="Булки" id="one"></IngredientsCategory>
**Необходимо исправить** 
Использовать числительные - плохая практика. Это может усложнить понимание кода и его расширение. Тут в качестве айдишников вполне сойдут названия категорий.

2022-07-07 06:14 UTC, andryxxa93 commented on src/components/ingredient-details/IngredientDetails.jsx
> +}
**Можно лучше**
Это является повторением кода из `prop-types.js`. Чтобы избежать дублирования можно создать тип - включающий в себя эти поля и его уже добавить внутрь `ingredientPropTypes` и импортировать сюда.

2022-07-07 06:14 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +  }, [onClose]);
**Можно лучше**
Так как функция передаётся по ссылке, а при новом рендере будет создаваться новая функция и меняться ссылка, то useEffect будет считать, что зависимость обновилась. Тут можно оставить пустым массив в зависимостями, чтобы подписка происходила один раз при первом рендере.

2022-07-07 06:14 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +      if (evt.key === "Escape") {
**Здорово** 
Вы реализовали закрытие модальных окон помощью клика на оверлей и ESC!

2022-07-07 06:14 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +      document.removeEventListener('keydown', handleEscKeydown);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2022-07-07 21:38 UTC, EukleidesRUS commented on src/components/ingredient-details/IngredientDetails.jsx
> +}
Можно пример грамотной реализации этого момента? Как именно на практике вы это используете?

2022-07-08 14:18 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, ваша работа принята! Удачного продолжения обучения!

2022-07-13 17:23 UTC, merged